version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - '4566:4566'
      - '4571:4571'
    environment:
      - SERVICES=kinesis,lambda,firehose,s3,iam
      - DEBUG=1
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
